### PR TITLE
highlight support

### PR DESCRIPTION
**Pull request by mxp100**
Adding feature for highlighting in founded text
Example:
```php
            $highlight = new Highlight();
            $highlight->setTags(['<mark>'], ['</mark>']);
            $highlight->addField('title', ['matched_fields' => ['title']]);
            $highlight->addField('content', ['matched_fields' => ['content']]);

            $highlight->setParameters([
                'require_field_match' => false,
                'force_source' => true,
            ]);


            $search->query->addHighlight($highlight);
```

### CODE REVIEW

**Comment by mxp100** [comment]
if needed, i add example to readme.md

**Comment by sleimanx2** [comment]
Yes ! , I think we should add a `highlight` method on the builder, for a more consistent api.
and please some test

**Comment by mxp100** [comment]
may be i added to builder?

**Comment by sleimanx2** [comment]
yes makes sense.

**Comment by mxp100** [comment]
i added to builder

**Comment by XavRsl** [comment]
Hi !
Great to see highlights integrated. Can you make a release ??

Thanks

**Comment by mxp100** [comment]
branch merged to master and work

**Pull request merged**
